import fs from 'fs';
import path from 'path';
import ignore from 'ignore';
import glob from 'fast-glob';

export interface DiscoveredFile {
  absolutePath: string;
  relativePath: string;
}

/**
 * Discovery mode controls how aggressively we filter directories/files before
 * parsing. Modes are layered defaults — finer-grained `includeVendor` /
 * `includeGenerated` toggles can still override the mode's vendor/generated
 * decisions, and `.strataignore` rules apply on top of all of them.
 *
 *   - `full`     index everything we can parse (only build/meta and .git skipped)
 *   - `standard` skip vendor + generated by default (current historical default)
 *   - `fast`     standard + skip docs/examples/static/assets/migrations — aimed
 *                at iterative agent loops where most non-source dirs are dead
 *                weight
 *
 * Default is `standard`; `fast` is a deliberate opt-in for power users on
 * very large repos where they want indexing as cheap as possible.
 */
export type DiscoveryMode = 'full' | 'standard' | 'fast';

export interface DiscoveryOptions {
  /**
   * If true, vendored / generated directories that the default ignore list
   * would skip are included in discovery. Vendored/generated classification
   * still happens at index time — this just lets the user inspect what
   * Strata would normally hide. Off by default; the README and master guide
   * describe this as the "I really do want vendored code" escape hatch.
   */
  includeVendor?: boolean;
  includeGenerated?: boolean;
  /**
   * Discovery aggressiveness. Defaults to 'standard'. See `DiscoveryMode`.
   */
  mode?: DiscoveryMode;
}

// Globally-skipped paths that are never source code (build outputs, IDE
// state, VCS metadata). These are unconditional — `includeVendor` /
// `includeGenerated` do NOT re-enable them. The user can override by adding
// a `!pattern` line in `.strataignore`.
const BUILD_AND_META_IGNORE = [
  'node_modules', '.git', '.hg', '.svn',
  'dist', 'build', 'out', '.next', '.nuxt', '__pycache__',
  '*.min.js', '*.min.css', '*.bundle.js',
  '*.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml',
  // Build outputs across other ecosystems. `target/` is universally Rust
  // (`cargo build`), `obj/` is .NET, `cmake-build-*` is JetBrains/CLion,
  // `_build/` is Erlang/Elixir and some doc generators. Not adding `bin/`
  // here — TypeScript-main and others keep entry scripts there.
  'target/**', '**/target/**',
  'obj/**', '**/obj/**',
  'cmake-build-*/**', '**/cmake-build-*/**',
  '_build/**', '**/_build/**',
  '.gradle/**', '**/.gradle/**',
  '.cache/**',
  '.idea/**', '.vs/**',
  // Unreal-specific build outputs (won't exist in a clean checkout but cheap
  // to add defensively for users who built before indexing).
  'Intermediate/**', '**/Intermediate/**',
  'Saved/**', '**/Saved/**',
  'DerivedDataCache/**',
];

// Vendored dependency roots — discovery-time skip by default, but classified
// even when included. Match both the top level and any nested depth (Godot
// uses `thirdparty/`, Unreal uses `Engine/Source/ThirdParty/`, etc.).
const VENDOR_IGNORE = [
  'vendor/**', '**/vendor/**',
  'vendored/**', '**/vendored/**',
  'Vendored/**', '**/Vendored/**',
  'third_party/**', '**/third_party/**',
  'thirdparty/**', '**/thirdparty/**',
  'ThirdParty/**', '**/ThirdParty/**',
];

// Generated-code patterns that don't earn a place in default indexing. Same
// "skip-by-default, classify-when-included" model as vendored code.
const GENERATED_IGNORE = [
  '*.pb.go', '*.pb.ts', '*.pb.h', '*.pb.cc',
  '*.generated.h', '*.gen.cpp', '*.gen.h',
];

// Extra skips active only under `--mode fast`. These directories rarely
// contain source code that contributes to the call graph — examples are
// either demos that re-import from src, docs/static/assets are non-code, and
// migrations are usually flat SQL or schema-only Python. Skipping them in
// fast mode trims discovery and parse cost meaningfully on large monorepos.
// Conservative on purpose: anything that might contain real call edges
// (`tests/`, `src/`, `lib/`) stays indexed even in fast mode.
const FAST_MODE_EXTRA_IGNORE = [
  'docs/**', '**/docs/**',
  'examples/**', '**/examples/**',
  'example/**', '**/example/**',
  'assets/**', '**/assets/**',
  'static/**', '**/static/**',
  'public/**', '**/public/**',
  'media/**', '**/media/**',
  'fixtures/**', '**/fixtures/**',
  'testdata/**', '**/testdata/**',
  'migrations/**', '**/migrations/**',
];

export async function discoverFiles(repoRoot: string, options: DiscoveryOptions = {}): Promise<DiscoveredFile[]> {
  const absRoot = path.resolve(repoRoot);
  const mode: DiscoveryMode = options.mode ?? 'standard';
  // `full` mode flips both include flags ON regardless of caller intent. We
  // still honor explicit `includeVendor=false` from a caller, but the typical
  // use of `--mode full` is "index literally everything", so the default
  // there is to include them.
  const includeVendor = options.includeVendor ?? (mode === 'full');
  const includeGenerated = options.includeGenerated ?? (mode === 'full');

  const skip = [...BUILD_AND_META_IGNORE];
  if (!includeVendor)    skip.push(...VENDOR_IGNORE);
  if (!includeGenerated) skip.push(...GENERATED_IGNORE);
  if (mode === 'fast')   skip.push(...FAST_MODE_EXTRA_IGNORE);

  // Build ignore rules from .gitignore + optional .strataignore. The two are
  // separate intentionally — .gitignore controls what's committed (often
  // includes build outputs that we ALSO want hidden) while .strataignore is
  // for repo-specific tweaks that don't belong in version control rules
  // (e.g. "don't index our `examples/` folder").
  const ig = ignore();
  const gitignorePath = path.join(absRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    ig.add(fs.readFileSync(gitignorePath, 'utf8'));
  }
  const strataignorePath = path.join(absRoot, '.strataignore');
  if (fs.existsSync(strataignorePath)) {
    ig.add(fs.readFileSync(strataignorePath, 'utf8'));
  }

  // Glob for source files in supported languages
  const entries = await glob(
    [
      '**/*.py', '**/*.pyw',
      '**/*.ts', '**/*.tsx',
      '**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs',
      '**/*.go',
      '**/*.java',
      '**/*.rs',
      '**/*.c',
      '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.c++',
      '**/*.hpp', '**/*.hh', '**/*.h++', '**/*.h',
      '**/*.cs',
    ],
    {
      cwd: absRoot,
      ignore: skip,
      onlyFiles: true,
      followSymbolicLinks: false,
      dot: false,
    },
  );

  return entries
    .filter(rel => !ig.ignores(rel))
    .map(rel => ({
      absolutePath: path.join(absRoot, rel),
      relativePath: rel,
    }));
}
