import fs from 'fs';
import path from 'path';
import ignore from 'ignore';
import glob from 'fast-glob';

export interface DiscoveredFile {
  absolutePath: string;
  relativePath: string;
}

/**
 * Discovery mode controls how aggressively we filter directories/files before
 * parsing. Modes are layered defaults — finer-grained `includeVendor` /
 * `includeGenerated` toggles can still override the mode's vendor/generated
 * decisions, and `.seerignore` rules apply on top of all of them.
 *
 *   - `full`     index everything we can parse (only build/meta and .git skipped)
 *   - `standard` skip vendor + generated by default (current historical default)
 *   - `fast`     standard + skip docs/examples/static/assets/migrations — aimed
 *                at iterative agent loops where most non-source dirs are dead
 *                weight
 *
 * Default is `standard`; `fast` is a deliberate opt-in for power users on
 * very large repos where they want indexing as cheap as possible.
 */
export type DiscoveryMode = 'full' | 'standard' | 'fast';

export interface DiscoveryOptions {
  /**
   * If true, vendored / generated directories that the default ignore list
   * would skip are included in discovery. Vendored/generated classification
   * still happens at index time — this just lets the user inspect what
   * Seer would normally hide. Off by default; the README and master guide
   * describe this as the "I really do want vendored code" escape hatch.
   */
  includeVendor?: boolean;
  includeGenerated?: boolean;
  /**
   * Discovery aggressiveness. Defaults to 'standard'. See `DiscoveryMode`.
   */
  mode?: DiscoveryMode;
}

// Globally-skipped paths that are never source code (build outputs, IDE
// state, VCS metadata). These are unconditional — `includeVendor` /
// `includeGenerated` do NOT re-enable them.
const BUILD_AND_META_IGNORE = [
  'node_modules/**', '**/node_modules/**',
  '.git/**', '**/.git/**', '.hg/**', '**/.hg/**', '.svn/**', '**/.svn/**',
  'dist/**', '**/dist/**',
  'build/**', '**/build/**',
  'out/**', '**/out/**',
  '.next/**', '**/.next/**',
  '.nuxt/**', '**/.nuxt/**',
  '.svelte-kit/**', '**/.svelte-kit/**',
  '.turbo/**', '**/.turbo/**',
  'coverage/**', '**/coverage/**',
  '__pycache__/**', '**/__pycache__/**',
  '*.min.js', '*.min.css', '*.bundle.js',
  '*.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml',
  // Build outputs across other ecosystems. `target/` is universally Rust
  // (`cargo build`), `obj/` is .NET, `cmake-build-*` is JetBrains/CLion,
  // `_build/` is Erlang/Elixir and some doc generators. Not adding `bin/`
  // here — TypeScript-main and others keep entry scripts there.
  'target/**', '**/target/**',
  'obj/**', '**/obj/**',
  'cmake-build-*/**', '**/cmake-build-*/**',
  '_build/**', '**/_build/**',
  '.gradle/**', '**/.gradle/**',
  '.cache/**', '**/.cache/**',
  '.idea/**', '**/.idea/**',
  '.vs/**', '**/.vs/**',
  // Unreal-specific build outputs (won't exist in a clean checkout but cheap
  // to add defensively for users who built before indexing).
  'Intermediate/**', '**/Intermediate/**',
  'Saved/**', '**/Saved/**',
  'DerivedDataCache/**', '**/DerivedDataCache/**',
];

// Vendored dependency roots — discovery-time skip by default, but classified
// even when included. Match both the top level and any nested depth (Godot
// uses `thirdparty/`, Unreal uses `Engine/Source/ThirdParty/`, etc.).
const VENDOR_IGNORE = [
  'vendor/**', '**/vendor/**',
  'vendored/**', '**/vendored/**',
  'Vendored/**', '**/Vendored/**',
  'third_party/**', '**/third_party/**',
  'thirdparty/**', '**/thirdparty/**',
  'ThirdParty/**', '**/ThirdParty/**',
];

// Generated-code patterns that don't earn a place in default indexing. Same
// "skip-by-default, classify-when-included" model as vendored code.
const GENERATED_IGNORE = [
  '*.pb.go', '**/*.pb.go',
  '*.pb.ts', '**/*.pb.ts',
  '*.pb.h', '**/*.pb.h',
  '*.pb.cc', '**/*.pb.cc',
  '*.generated.h', '**/*.generated.h',
  '*.gen.cpp', '**/*.gen.cpp',
  '*.gen.h', '**/*.gen.h',
];

// Extra skips active only under `--mode fast`. These directories rarely
// contain source code that contributes to the call graph — examples are
// either demos that re-import from src, docs/static/assets are non-code, and
// migrations are usually flat SQL or schema-only Python. Skipping them in
// fast mode trims discovery and parse cost meaningfully on large monorepos.
// Conservative on purpose: anything that might contain real call edges
// (`tests/`, `src/`, `lib/`) stays indexed even in fast mode.
const FAST_MODE_EXTRA_IGNORE = [
  'docs/**', '**/docs/**',
  'examples/**', '**/examples/**',
  'example/**', '**/example/**',
  'assets/**', '**/assets/**',
  'static/**', '**/static/**',
  'public/**', '**/public/**',
  'media/**', '**/media/**',
  'fixtures/**', '**/fixtures/**',
  'testdata/**', '**/testdata/**',
  'migrations/**', '**/migrations/**',
];

interface IgnoreLayer {
  dir: string;
  file: string;
  ig: ReturnType<typeof ignore>;
}

function normalizeRelPath(p: string): string {
  return p.replace(/\\/g, '/');
}

function ignoreLayerDepth(layer: IgnoreLayer): number {
  return layer.dir ? layer.dir.split('/').length : 0;
}

async function loadIgnoreLayers(absRoot: string, skip: string[]): Promise<IgnoreLayer[]> {
  const layers: IgnoreLayer[] = [];
  const addLayer = (relFile: string): void => {
    const normRel = normalizeRelPath(relFile);
    const absFile = path.join(absRoot, ...normRel.split('/'));
    if (!fs.existsSync(absFile)) return;
    const raw = fs.readFileSync(absFile, 'utf8');
    if (!raw.trim()) return;
    const dir = path.posix.dirname(normRel);
    const ig = ignore();
    ig.add(raw);
    layers.push({
      dir: dir === '.' ? '' : dir,
      file: path.posix.basename(normRel),
      ig,
    });
  };

  addLayer('.gitignore');
  addLayer('.seerignore');

  const nested = await glob(['**/.gitignore', '**/.seerignore'], {
    cwd: absRoot,
    ignore: skip,
    onlyFiles: true,
    followSymbolicLinks: false,
    dot: true,
  });

  for (const rel of nested.sort()) {
    const normRel = normalizeRelPath(rel);
    if (normRel === '.gitignore' || normRel === '.seerignore') continue;
    if (isIgnoredByLayers(normRel, layers)) continue;
    addLayer(normRel);
  }

  return layers.sort((a, b) =>
    ignoreLayerDepth(a) - ignoreLayerDepth(b)
    || a.dir.localeCompare(b.dir)
    || a.file.localeCompare(b.file),
  );
}

function isIgnoredByLayers(rel: string, layers: IgnoreLayer[]): boolean {
  const normRel = normalizeRelPath(rel);
  let ignored = false;
  for (const layer of layers) {
    if (layer.dir && normRel !== layer.dir && !normRel.startsWith(`${layer.dir}/`)) continue;
    const subPath = layer.dir ? normRel.slice(layer.dir.length + 1) : normRel;
    if (!subPath) continue;
    const result = layer.ig.test(subPath);
    if (result.ignored) ignored = true;
    if (result.unignored) ignored = false;
  }
  return ignored;
}

export async function discoverFiles(repoRoot: string, options: DiscoveryOptions = {}): Promise<DiscoveredFile[]> {
  const absRoot = path.resolve(repoRoot);
  const mode: DiscoveryMode = options.mode ?? 'standard';
  // `full` mode flips both include flags ON regardless of caller intent. We
  // still honor explicit `includeVendor=false` from a caller, but the typical
  // use of `--mode full` is "index literally everything", so the default
  // there is to include them.
  const includeVendor = options.includeVendor ?? (mode === 'full');
  const includeGenerated = options.includeGenerated ?? (mode === 'full');

  const skip = [...BUILD_AND_META_IGNORE];
  if (!includeVendor)    skip.push(...VENDOR_IGNORE);
  if (!includeGenerated) skip.push(...GENERATED_IGNORE);
  if (mode === 'fast')   skip.push(...FAST_MODE_EXTRA_IGNORE);

  // Build ignore rules from root and nested .gitignore / .seerignore files.
  // Nested rules are evaluated relative to their own directory.
  const ignoreLayers = await loadIgnoreLayers(absRoot, skip);

  // Glob for source files in supported languages
  const entries = await glob(
    [
      '**/*.py', '**/*.pyw',
      '**/*.ts', '**/*.tsx',
      '**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs',
      '**/*.go',
      '**/*.java',
      '**/*.rs',
      '**/*.c',
      '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.c++',
      '**/*.hpp', '**/*.hh', '**/*.h++', '**/*.h',
      '**/*.cs',
    ],
    {
      cwd: absRoot,
      ignore: skip,
      onlyFiles: true,
      followSymbolicLinks: false,
      dot: false,
    },
  );

  // Stable order across runs is a correctness requirement: file IDs are
  // AUTOINCREMENT, and tests/scale invariants depend on the same input
  // producing the same IDs. `fast-glob` on Windows returns files in MFT/
  // FS-cache order, which is not stable run-to-run. Sort here so every
  // downstream stage — the byte semaphore window, parser-worker dispatch,
  // SQLite inserts — sees the same sequence on every invocation.
  return entries
    .filter(rel => !isIgnoredByLayers(rel, ignoreLayers))
    .sort()
    .map(rel => ({
      absolutePath: path.join(absRoot, rel),
      relativePath: rel,
    }));
}
